// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
// ------------------------------------------------------------

#![doc = include_str!("../README.md")]

/// Service Fabric Windows Runtime metadata (`Windows.ServiceFabric.*`),
/// regenerated by `just generate` from the committed IDL sources.
pub static METADATA: &[u8] = include_bytes!("../Windows.ServiceFabric.winmd");
