// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
// ------------------------------------------------------------

#![doc = include_str!("../README.md")]

/// Service Fabric Windows Runtime metadata (`Windows.ServiceFabric.*`),
/// regenerated by `just generate` from the committed IDL sources. This is the
/// same content as the committed
/// `.windows/winmd/Windows.ServiceFabric.winmd` artifact.
pub static METADATA: &[u8] = include_bytes!("../../.windows/winmd/Windows.ServiceFabric.winmd");
